### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Maikuolan** [InvisbleMario/Toontown-Community#3]
I don't play this game, but, while browsing GitHub repos earlier today, I stumbled across yours, and I've noticed a few small typos in some of your files.

I can fix these for you quickly and send back a pull request if you'd like. :-)

**Comment by InvisbleMario** [comment]
This is welcomed greatly! Honestly you should get into it. It's pretty much an addictive grind. Also if anything calls it by it's misspelled name please modify that also. Thanks!
