### ISSUE TITLE
Toontown.exe flagged as malware

### ISSUE THREAD

**Issue by Maikuolan** [InvisbleMario/Toontown-Community#5]
https://www.hybrid-analysis.com/sample/9897641a49e76ff243ea800f780758f6784fc79425ba3c9f9ca1689e75d53290?environmentId=1

https://www.virustotal.com/en/file/9897641a49e76ff243ea800f780758f6784fc79425ba3c9f9ca1689e75d53290/analysis/

Might want to look into this. :-)

**Comment by InvisbleMario** [comment]
This was a reoccuring issue from the source itself. Can't I file an investigation to fix it?

**Comment by InvisbleMario** [comment]
Thanks for your help so far even if you don't play toontown. :)

**Comment by Maikuolan** [comment]
No problem, happy to help. :-)

**Comment by InvisbleMario** [comment]
I'll remove it from the github for now until i fix it.

**Comment by Maikuolan** [comment]
Okay.
